repos:
  - repo: https://github.com/sourcery-ai/sourcery
    rev: v1.9.0
    hooks:
      - id: sourcery
        # The best way to use Sourcery in a pre-commit hook:
        # * review only changed lines:
        # * omit the summary
        args: [ --diff=git diff main, --no-summary ]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.0.289
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        stages: [ commit ]
        language: system
        entry: python -m pytest .
        types: [ python ]
        pass_filenames: false
        always_run: true
      - id: pytest-cov
        name: pytest-cov
        stages: [ push ]
        language: system
        entry: python -m pytest --cov-fail-under=100 --cov=.
        types: [ python ]
        pass_filenames: false
        always_run: true
      - id: mutmut
        name: mutmut
        stages: [ push ]
        language: system
        entry: python -m mutmut run
        types: [ python ]
        pass_filenames: false
        always_run: true
      - id: mypy
        name: mypy
        stages: [ commit ]
        language: system
        entry: python -m mypy src/
        types: [ python ]
        pass_filenames: false
        always_run: true